---
title: "Homework Four"
output: html_document
---

# Homework Four: Due Sept. 23  at 5 pm.

First, download your homework. In your RStudio, fill in the below command:

```{r, eval = FALSE}

```

# Question One:

Take a look at [this](https://github.com/ropensci/treedata.table) package. Reading the documentation, what is the primary goal of this package? 

```
The purpose of this package is to make working with phylogenic data easier in R. It allows for easy and efficant use of trait data and phylogenetic trees.
```

# Question Two

Where in this package is the actual code stored? How do you know?

```
The code for this package is stored in the directories on the GitHub website in the R directory. We know this because we have the option to download the code from the website and we can go into the files on Github and see the code writen.  
```

# Question 3

When you look into the code, are you able to understand any of it? What is one thing the authors could do to make the code more understandable?

```
looking through the code there are some functions and argument that look familiar, such as making functions or assigning values to vectors, but most of what the code is actually doing, I do not understand. It looks like some notes where writen in # at the top of the code. For other people working on the code these probably make a little more sense but for someone new to coding, fuller and more in depth notes may be helpful.
```

# Question 4

What are the other directories in the package? What do they contain?

```
.grapghics. This contains png's of logos on the read.me page. 
test is most likely contains data that test if the code functions properly. 
.ci seems to have code that sets up the webpage that presents the package.
.dev is a directory for developer to talk to one another
doc is a directory most likely used to store documents that were refrenced when writing the code
data appears to house a sample data set to test the code
pkgdown/favicon seems to be filled with various pictures of the icon used on the website page
```

# Question 5

Do you trust that this package does what it says it is doing? Why or why not? 

```
Yes, it is peer reviewed and have authors who make frequent contributions. The page also includes graphics that show treedata.table running against other packages.
```

# Question 6

Have a look at [these](https://libguides.bc.edu/dataplan/best_practices) data storage best practices from Boston College. Have this read by Sept. 27 as we will use this in an activity.

## Master's Students

Find a package that does something you'd like to do for your dissertation. Apply the steps above to this package to evaluate its reliability.
